apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/trustyai-explainability/trustyai-explainability?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[dev,main]"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: opendatahub-builds
    appstudio.openshift.io/component: odh-trustyai-service-ci
    pipelines.appstudio.openshift.io/type: build
  name: trustyai-explainability-on-pull-request
  namespace: open-data-hub-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/opendatahub/odh-trustyai-service:odh-pr
  - name: dockerfile
    value: Dockerfile
  - name: path-context
    value: .
  - name: image-expires-after
    value: 5d
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/opendatahub-io/odh-konflux-central.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipeline/multi-arch-container-build.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-odh-trustyai-service
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
